# Generated by Django 5.0 on 2024-08-16 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('alpha_2', models.CharField(max_length=2, unique=True)),
                ('alpha_3', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'db_table': 'countries',
                'unique_together': {('id', 'name', 'alpha_2', 'alpha_3')},
            },
        ),
        migrations.CreateModel(
            name='CurrencySymbolModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('character', models.CharField(max_length=6, unique=True)),
                ('decimal_value', models.PositiveIntegerField(unique=True)),
                ('unicode_value', models.CharField(max_length=8, unique=True)),
                ('html_entity', models.CharField(blank=True, max_length=10, null=True)),
                ('html_code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'currency_symbols',
                'unique_together': {('character', 'decimal_value', 'unicode_value')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=3, null=True)),
                ('symbol', models.ManyToManyField(blank=True, to='utils.currencysymbolmodel')),
            ],
            options={
                'db_table': 'currencies',
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(unique=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('imageurl', models.TextField(blank=True, null=True)),
                ('headline', models.TextField(blank=True, null=True)),
                ('publishdate', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_data',
                'unique_together': {('url', 'id')},
            },
        ),
        migrations.CreateModel(
            name='FrequentData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('shorturl', models.TextField(blank=True, null=True, unique=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('section', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('imageurl', models.TextField(blank=True, null=True)),
                ('headline', models.TextField(blank=True, null=True)),
                ('wordcount', models.IntegerField(blank=True, null=True)),
                ('publishdate', models.DateTimeField()),
                ('htmlbody', models.CharField(blank=True, null=True)),
                ('nohtmlbody', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'frequent_data',
                'unique_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ArticleAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accessed_ip', models.CharField(blank=True, max_length=39)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.frequentdata')),
            ],
            options={
                'db_table': 'article_access',
            },
        ),
        migrations.CreateModel(
            name='StockMarketsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mnemonic', models.CharField(max_length=7)),
                ('mic', models.CharField(max_length=6, unique=True)),
                ('operating_mic', models.CharField(max_length=6)),
                ('mcc', models.CharField(max_length=4)),
                ('lei', models.CharField(max_length=20)),
                ('lei_name', models.CharField(max_length=255)),
                ('market_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('timezone_name', models.CharField(max_length=34, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.countrymodel', to_field='alpha_2')),
            ],
            options={
                'db_table': 'stock_exchanges',
                'unique_together': {('mnemonic', 'mic', 'operating_mic', 'lei', 'mcc', 'city')},
            },
        ),
        migrations.CreateModel(
            name='StockSymbolsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=120)),
                ('symbol_type', models.CharField(choices=[('COM', 'Common Stock'), ('PRF', 'Preferred Stock'), ('IND', 'Market Index'), ('ETF', 'Exchange Traded Fund'), ('OTH', 'Other')], default='COM', max_length=3)),
                ('google', models.CharField(blank=True, max_length=20, null=True)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('bbg', models.CharField(blank=True, max_length=12, null=True)),
                ('cusip', models.CharField(blank=True, max_length=9, null=True)),
                ('isin', models.CharField(blank=True, max_length=12, null=True)),
                ('sedol', models.CharField(blank=True, max_length=7, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.currencymodel', to_field='code')),
                ('exchange_mic', models.ManyToManyField(related_name='symbols', to='utils.stockmarketsmodel')),
            ],
            options={
                'db_table': 'stock_symbols',
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.stocksymbolsmodel', to_field='google')),
            ],
            options={
                'db_table': 'stock_market_prices',
            },
        ),
        migrations.AddConstraint(
            model_name='stocksymbolsmodel',
            constraint=models.UniqueConstraint(fields=('google',), name='unique_google'),
        ),
    ]
