# Generated by Django 5.0 on 2024-08-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['id', 'symbol'], name='id_symbol_idx'),
        ),
    ]
