# Generated by Django 5.0 on 2024-08-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_marketdata_id_symbol_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
