# Generated by Django 5.0 on 2024-08-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_alter_marketdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
