# Generated by Django 5.0 on 2024-08-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_marketdata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
