# Generated by Django 5.0 on 2024-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_alter_marketdata_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stocksymbolsmodel',
            index=models.Index(fields=['google'], name='google_idx'),
        ),
    ]
