# Generated by Django 5.0 on 2024-08-22 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_stocksymbolsmodel_google_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDataHistoric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trading_date', models.DateField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('symbol_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.stocksymbolsmodel', to_field='google')),
            ],
            options={
                'db_table': 'stock_market_prices_historic',
                'indexes': [models.Index(fields=['symbol_id'], name='symbol_id_idx'), models.Index(fields=['trading_date'], name='trading_date_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='marketdatahistoric',
            constraint=models.UniqueConstraint(fields=('symbol_id', 'trading_date'), name='unique_symbol_id_trading_date'),
        ),
    ]
