# Generated by Django 5.0 on 2024-08-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_remove_marketdata_id_symbol_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marketdatahistoric',
            name='symbol_id_idx',
        ),
    ]
