# Generated by Django 5.0 on 2024-08-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_remove_marketdatahistoric_symbol_id_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marketdatahistoric',
            name='trading_date_idx',
        ),
    ]
