# Generated by Django 5.0 on 2024-08-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_remove_marketdatahistoric_trading_date_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marketdatahistoric',
            index=models.Index(fields=['trading_date'], name='smp_historic_trading_date_idx'),
        ),
    ]
