# Generated by Django 5.0 on 2024-08-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_marketdatahistoric_smp_historic_trading_date_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marketdata',
            name='stock_market_prices_symbol_idx',
        ),
    ]
