# Generated by Django 5.1 on 2024-09-14 13:05

import django.db.models.deletion
import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_marketdatamatview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMetaAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polarity_pos', models.DecimalField(decimal_places=5, max_digits=6, validators=[utils.models.betweenNegOneAndPosOneValidator])),
                ('polarity_neu', models.DecimalField(decimal_places=5, max_digits=6, validators=[utils.models.betweenNegOneAndPosOneValidator])),
                ('polarity_neg', models.DecimalField(decimal_places=5, max_digits=6, validators=[utils.models.betweenNegOneAndPosOneValidator])),
                ('polarity_comp', models.DecimalField(decimal_places=5, max_digits=6, validators=[utils.models.betweenNegOneAndPosOneValidator])),
                ('n_sentences', models.IntegerField(default=1, max_length=4)),
                ('readability_flesch_reading_ease', models.DecimalField(decimal_places=2, max_digits=5, validators=[utils.models.betweenOneAndHundredValidator])),
                ('readability_dale_chall_readability_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[utils.models.betweenOneAndHundredValidator])),
                ('readability_time_to_read', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ner_countries', models.JSONField(blank=True, default=dict, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.frequentdata')),
            ],
            options={
                'db_table': 'article_meta_analytics',
            },
        ),
    ]
