# Generated by Django 5.1 on 2024-09-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_articlemetaanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemetaanalytics',
            name='n_sentences',
            field=models.IntegerField(default=1),
        ),
    ]
