# Generated by Django 5.1 on 2024-09-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_alter_articlemetaanalytics_n_sentences'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemetaanalytics',
            name='ner_keywords',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
