# Generated by Django 5.1 on 2024-09-17 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_articlemetaanalytics_ner_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemetaanalytics',
            name='article_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='articlemetaanalytics',
            name='article_embedding_norm',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True),
        ),
    ]
