# Generated by Django 5.1 on 2024-09-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0018_articlemetaanalytics_article_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemetaanalytics',
            name='article_embedding_norm',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
    ]
