# Generated by Django 5.1 on 2024-09-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0019_alter_articlemetaanalytics_article_embedding_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemetaanalytics',
            name='wordcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
