# Generated by Django 5.1 on 2024-10-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0022_alter_newslettersubscribermodel_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articlemetaanalytics',
            index=models.Index(fields=['id'], name='analytics_id_idx'),
        ),
        migrations.AddIndex(
            model_name='articlemetaanalytics',
            index=models.Index(fields=['article'], name='analytics_article_id_idx'),
        ),
        migrations.AddIndex(
            model_name='frequentdata',
            index=models.Index(fields=['id'], name='article_id_idx'),
        ),
    ]
