# Generated by Django 5.1 on 2024-10-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0023_articlemetaanalytics_analytics_id_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accessed_ip', models.CharField(blank=True, max_length=39)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_tracker',
            },
        ),
    ]
